name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint with flake8
      run: |
        poetry install
        poetry run flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
